### ISSUE TITLE
address datatype formatter implemented as int

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-contracts.js#1]
Hi,
Working fine for my current proof of concept, but encountered a small shortcoming in defining a function with address data type as an input. Fails with a BigInt conversion error.
Could be by design, but guessing that there should be a formatInputAddress in solidity/coder.js and formatters..

currently (coders/213):
        inputFormatter: f.**formatInputInt**,
        outputFormatter: f.formatOutputAddress

Could also create a pull request if possible..

Thanks

**Comment by androlo** [comment]
Thanks. I will fix. 

Fyi: It is Int in web3 because Eth prepends all hex strings with 0x which we do not. A hex string starting with 0x is valid syntax for BigNumbers, but it throws because without the 0x it is just a malformed decimal string. Slipped past the test it seems.

In the meantime it should work if you prepend that particular address with 0x before passing it in, or wait to tomorrow and i'll update.

**Comment by androlo** [comment]
I will likely add a formatInputAddress that only allows hex strings - both those that are prepended with 0x and those that aren't. This is just weird.

**Comment by rguikers** [comment]
Thanks Andreas.. POC ready to fly now...

**Comment by androlo** [comment]
nice.
