### ISSUE TITLE
Bigints as a hex string

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#4]
I am running into an issue where the contract takes a uint but i'm supplying the uint as a hex string and it gets the following issue

```
{ [BigNumber Error: new BigNumber() not a number: 37236DF251AB70022B1DA351F08A20FB52443E37] name: 'BigNumber Error' }
```

We should be able to submit ints and uints as hex (interpreting them as numbers instead of byte arrays)

**Comment by androlo** [comment]
there's no fix to this. you can't pass a bignum a non prefixed string since BigNumber accepts decimal strings as well, and decimal is the default. To do it automatically you put '0x' in front of hex strings. (if you need it to be without '0x' then create a big number manually and set the radix to 16 and it'll then be automatically parsed as a hex string).
